### ISSUE TITLE
dependencies conflict  when  I run "react-native run-android"

### ISSUE THREAD

**Issue by softtecsz** [bitbat-io/ethereum-light-wallet-android#5]
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-v4' has different version for the compile (26.1.0) and runtime (27.1.0) classpath. You should manually set the same version via DependencyResolution

thanks  for  your  attention!

**Comment by hkxicor** [comment]
try updating from 26.1.0 to 27.1.0 manually.

**Comment by softtecsz** [comment]
it works affer I update  the  version !thanks!
